// apps/backend/src/infrastructure/web/controllers/ItemController.ts

import { Request, Response, NextFunction } from 'express';
import { z } from 'zod';
import { ItemService } from '../../../core/application/services/ItemService';
import { getActorUserId, getTenantId } from '../middlewares/context';
import { createAuditLog } from '../../database/repositories/mongo/auditLogRepository'; // Keep for now, will refactor audit log later

export class ItemController {
  private readonly createItemBodySchema = z.object({
    name: z.string().trim().min(1).max(200),
  });

  constructor(private readonly itemService: ItemService) {}

  async getItems(req: Request, res: Response, next: NextFunction) {
    try {
      const tenantId = getTenantId(req);
      const items = await this.itemService.getAllItems(tenantId);
      res.json(items);
    } catch (err) {
      next(err);
    }
  }

  async createItem(req: Request, res: Response, next: NextFunction) {
    try {
      const tenantId = getTenantId(req);
      const actorUserId = getActorUserId(req);
      const body = this.createItemBodySchema.parse(req.body);

      const item = await this.itemService.createItem({
        id: '', // Will be generated by the service/repository
        name: body.name,
        tenantId,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdByUserId: actorUserId,
        updatedByUserId: actorUserId,
      });

      // Temporarily keeping audit log here, will refactor to a dedicated service later
      await createAuditLog({
        action: 'item.created',
        payload: { itemId: item.id },
        tenantId,
        actorUserId,
      });

      res.status(201).json(item);
    } catch (err) {
      next(err);
    }
  }
}
